### PR TITLE
v210403.0.7 - Debian image

### PR DESCRIPTION
**Pull request by Dexus**
## Summary

Summarize your PR. If it involves visual changes, include a screenshot or GIF.

### Checklist

Delete any items that are not applicable to this PR.

- [ ] [Update Documentation](https://github.com/Secure-Compliance-Solutions-LLC/gitbook) was added for features that require explanation or tutorials

### Enhancements:
 - build mulipte architectures (AMD64 & ARM64)

### Fixed Bug/Issues solved:

- #263 
- #267 
- #273 
- #279 
- #280 
- #281
- #295 

### Breaking Changes:

Switch from Alpine Image to Debian 10 base image. This is the only full supported OS from Greenbone.

### Release Size:
```
ghcr.io/secure-compliance-solutions-llc/gvm-docker   pr-262-data-full      9d1c3a54a3f3   13 hours ago   6.02GB
ghcr.io/secure-compliance-solutions-llc/gvm-docker   pr-262-data           3f4cd56bf530   13 hours ago   5.73GB
ghcr.io/secure-compliance-solutions-llc/gvm-docker   pr-262-full           bb0a6338a708   14 hours ago   1.28GB
ghcr.io/secure-compliance-solutions-llc/gvm-docker   pr-262                11f768aee2e1   15 hours ago   991MB
```
Now all `-data` images are full pre-initialized (with available data from the build time)

## Notice
Pre Initialized (`-data`) images, have a web ui password: `adminpassword` and should be changed after the deployment.
Also the Postgres got a default password: `none`

### CODE REVIEW

**Comment by austinsonger** [comment]
@Dexus We shouldn't be pushing images to github registry until this pull request is ready to be merged with master. Is it ready to be merged?

**Comment by Dexus** [comment]
It is ready for merge and release after it we should update the versions and release again.

Was a bit busy to finish other things that I had on my TODO.

But for now it is good to go.

**Comment by Dexus** [comment]
> @Dexus We shouldn't be pushing images to github registry until this pull request is ready to be merged with master. Is it ready to be merged?

I need to test the images one public CR so everything ist pushed to GitHub. Even it is development state.

**Comment by austinsonger** [comment]
Okay when its good just click `Ready to Review`

**Comment by austinsonger** [comment]
@Dexus Does any documentation need to be updated?

**Comment by Dexus** [comment]
Need to check on the weekend.

Von meinem iPhone gesendet

**Pull request merged**
