### PR TITLE
Move to Alpine Image

### LINKED ISSUE #203: [Bug] authorized_keys: No such file or directory
**Describe the bug**
When using ./add-scanner.sh to create a remote scanner on the host, I get the error "./add-scanner.sh: line 12: /data/scanner-ssh-keys/authorized_keys: No such file or directory".

**To Reproduce**
1. run command "docker exec -it gvm ./add-scanner.sh
2. Input scanner Name
3. Input scanner ID
4. Input scanner Public Key
5. See Error.

**Expected behavior**
The scanner is added, but I am getting the below on the remote scanner I presume because the key isn't being saved and therefore isn't an authorized key:

On the remote scanner:
==> /usr/local/var/log/gvm/ssh-connection.log <==
Permission denied, please try again.
Permission denied, please try again.
gvm@192.168.x.x: Permission denied (publickey,password).

**Host Device:**
 - OS: Ubuntu 
 - Version: 20.04 LTS

**Additional context**
Command used to add remote scanner:

docker run --detach --volume scanner:/data --env MASTER_ADDRESS=192.168.[removed].[removed] --env MASTER_PORT=22 --name scanner securecompliance/openvas
8f1ef9729a338983b2858a288b65ac23c5354c32aab2269789742d57bc016ade

### LINKED ISSUE #205: [Bug] No config is available if the rsync is disallowed/blocked by firewall. Wrong Path of GVMD from data.tar.xz
**Describe the bug**
pre-sync data.tar.gz gvmd-data is not copied to the correct path.

**To Reproduce**
1. disallow rsync
2. start the container without existing data
3. open the Webinterface and look for the configs - nothing is there

**Expected behavior**
Copy pre-sync data from the data.tar.xz to the correct folder/path

**Additional context**
Latest Image Version and prev. are affacted.

PR #204 will fix it.

### LINKED ISSUE #206: [Bug] Unstable on high load systems
**Describe the bug**
If the server on which this container is running comes under heavy pressure, processes like ospd-openvas die.

**To Reproduce**
1. Have a big server with muchrum and much CPU
2. Start some scanns
3. Let this run for some days and keep the mashine under pressure, also RAM etc.
4. (you can also do it by hand from HV side - kill `ospd-openvas` like OOM would do....)
4. when you look to the webinterface you will see some about scans and this is the step where you see `ospd-openvas` is died!
5. See error - look into the Container and look for `ospd-openvas` all gone

**Expected behavior**
I recommend Supervisor with an initialization script that monitors and restarts the processes. Without monitoring you don't get to know about dead processes in the container.

**Additional context**
Latest Version and before affacted.

### PR DESCRIPTION
**Pull request by Dexus**
# What does this PR:

- Use the latest Alpine Version under Major Version 3 like 3.14 as of the current date. 
- Fix the "mv: inter-device move failed" error which can occur under certain circumstances.
- Add a initial data.tar.gz - no generator yet created - will follow by seperate PR
- No Symlink-fu keep the setup as simple as possible - maybe this needs a bit discuss -> if symlink MUST be used, it would be good to keep the symlinks as low as possible not every subdir use direct the /var/lib/gvm (home) and /var/lib/openvas/plugins path - also for DB place the DB storage path direct to the volume.
- supervisord support
  - fix #206  
- postfix support

We have two build ways:
With build for initialize on container start (only ~ ~~435~~ 1100MB)

`docker build -f Dockerfile -t securecompliance/gvm:v21.04-latest-nodata -t securecompliance/gvm:latest  .`

or
With pre-initialized that can be used without extra volumes on startup (only ~ 1200MB)

`docker build -f Dockerfile --build-arg SETUP=1 -t securecompliance/gvm:v21.04-latest-withdata -t securecompliance/gvm:latest-withdata  .`

## Milestones:
- [Downsize the GVM Docker Container](https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker/milestone/1)
- [Clean Up start.sh](https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker/milestone/15)
- [Postfix Mail Server for Delivering Email Notices from GVM](https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker/milestone/8)
- [Improve Structure git repo/docker build](https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker/milestone/3)

## Fixes ~~not~~ included:
- ~~Increase the web timeout - ref:#115 (bd6b15707e4fb58deeae1a384fc64e661ad82322) -> this can be done if we build the packages by our own~~
- ~~openvas-smb -> custom Build need (available on edge (latest: 21.4.1) -> but currently not for 21.4.1 (latest) -> own repo or should I add this here?~~

(Update: is integrated now via custom apk build)

# **Branking Change:**
- Logs of each service is not pushed to the `docker logs` each service has an own logfile.

# Missing currently:
- [x] Logrotate the files of gvm (`/var/log/gvm/*`)
- [x] [Update Documentation](https://github.com/Secure-Compliance-Solutions-LLC/gitbook)

# Fixed Bug/Issues solved:
- fixes #203
- fixes #204 
- fixes #205 
- fixes #206

# Size of different builds:
```
securecompliance/gvm               data-full            eac9487a5338   8 seconds ago       4.28GB
securecompliance/gvm               data                 463c9460ea80   12 minutes ago      2.21GB
securecompliance/gvm               no-data-full         35fc2436f515   18 minutes ago      2.58GB
securecompliance/gvm               latest               d7b61ea83ba1   18 minutes ago      511MB
securecompliance/gvm               no-data              d7b61ea83ba1   18 minutes ago      511MB
```
- `latest`, `data` and `no-data` - without `--build-arg OPT_PDF=1` don't use texlive deps for the optional PDF Report creation.
- `data-full` and `no-data-full` - with `--build-arg OPT_PDF=1` use texlive deps for the optional PDF Report creation.
- `no-data` - don't run the initial setup - this will done on first start.
- `data` - have a full installation that can be used without any volumes out of the box. It has already pre-synced NVT and gvmd data.

### CODE REVIEW

**Comment by Dexus** [comment]
It is building right now -  and so far it looks all good from my side.

**Review by austinsonger — APPROVED** [review]

**Comment by Dexus** [comment]
Maybe I get the chance to setup the latest releases of the gvm packages tomorrow.

**Comment by austinsonger** [comment]
> Maybe I get the chance to setup the latest releases of the gvm packages tomorrow.

@Dexus I created new branch for the new GVM release, I added a milestone regarding the new release as well.

**Comment by Dexus** [comment]
> > Maybe I get the chance to setup the latest releases of the gvm packages tomorrow.
> 
> @Dexus I created new branch for the new GVM release, I added a milestone regarding the new release as well.

@austinsonger new branch don't make sense in this repo, because the right place would be: https://github.com/Secure-Compliance-Solutions-LLC/GVM-APK-build

But for sure, will make a branch there.

**Comment by Dexus** [comment]
Using now the latest packages-

**Comment by austinsonger** [comment]
> Using now the latest packages-

I wouldn't push the package updates yet to the dev branch, I wanted to keep that separate from your original pull request, that's why I created a new branch for it the package updates, because that should be a completely new pull request.

**Comment by Dexus** [comment]
> > Using now the latest packages-
> 
> I wouldn't push the package updates yet to the dev branch, I wanted to keep that separate from your original pull request, that's why I created a new branch for it the package updates, because that should be a completely new pull request.

Okay, i reverted it.

**Comment by Dexus** [comment]
Any timeline when this will merged?

**Review by pixelsquared — APPROVED** [review]
LGTM

**Pull request merged**
