### PR TITLE
Fix firstrun and firstsync

### PR DESCRIPTION
**Pull request by Masaya-A**

### CODE REVIEW

**Comment by austinsonger** [comment]
@Masaya-A please provide reasoning of the pull request.

**Comment by Masaya-A** [comment]
The original paths are a root directory and are not a persistent directory (using --volume gvm-data:/data).
So, when updating the container, those files will be deleted and some commands which won't be needed will run again.

**Comment by austinsonger** [comment]
Resolves #187

**Comment by grantemsley** [comment]
That PR also moves firstrun which sets up symlinks and users for a fresh container. I think those steps still need to be done even if data already exists.

**Comment by Masaya-A** [comment]
@grantemsley You are correct! Thank you.
I've created a new PR #191 to revert them.

**Pull request merged**
