### PR TITLE
Create docker-compose file

### PR DESCRIPTION
**Pull request by grantemsley**
Adds a docker-compose.yml file for easy deployment.

Just change <path to data> to an appropriate path or docker volume, and
edit environment variables as needed.

### CODE REVIEW

**Comment by grantemsley** [comment]
> Nice this actually maps to one of our milestones, which I just added to this PR. We will review.

Yep, I saw that was in your milestones, and I was writing one for myself anyways, figured I may as well share!

**Comment by austinsonger** [comment]
@grantemsley 

If you can do a quick summary of how the [Docker Compose](https://github.com/Secure-Compliance-Solutions-LLC/gitbook/blob/master/openvas-greenbone-deployment-full-guide/docker-compose.md) file works. This will be for new people that may not be familiar. You may need to fork. Next time if you just add any relevant information regarding the pull request, I can create documentation from the pull request.

**Comment by grantemsley** [comment]
Sure, I'll add some instructions there and make a PR for the docs tomorrow.

**Comment by austinsonger** [comment]
@grantemsley 

Thanks. I just ask because keeping up with the documentation is probably the most difficult part of maintaining a github project.

**Pull request merged**
