### PR TITLE
GitHub action dexus 2

### PR DESCRIPTION
**Pull request by Dexus**
~~Currently WIP~~

This needs Repository/Organisation Secrets
- APKBUILD_RSA
- APKBUILD_RSA_PUB
- DOCKERHUB_TOKEN
- DOCKERHUB_USERNAME

Test Work for #226 

### Release to 2 registries

PR + Push + Tags (Release):
https://github.com/secure-compliance-solutions-llc/GVM-Docker/pkgs/container/gvm-docker

Only Release: (should go here)
https://hub.docker.com/r/securecompliance/gvm

### CODE REVIEW

**Comment by Dexus** [comment]
@pixelsquared @austinsonger 
It is final, and working.  Maybe yeah, we need to split it to own Action for apk build and remove the submodule frome here and OpenVAS, but at the end - we have now a working action.

**Comment by Dexus** [comment]
See: https://github.com/Dexus/GVM-Docker/actions/runs/1036922959

**Comment by pixelsquared** [comment]
Thanks for all your work here. The only question I have is: If we should move the APK build to GVM-APK-build repo?

**Comment by Dexus** [comment]
> Thanks for all your work here. The only question I have is: If we should move the APK build to GVM-APK-build repo?

Sure, I only create this to test and have a working setup for a quick release.

After it we can move this to the GVM-APK-build repo. I will do the PR there also, give me some minutes. So we can check if it works with the artefacts.

**Comment by pixelsquared** [comment]
I am good with merging this and then working on moving the APK build over. I just need to setup the secrets in this repo before I merge this.

**Comment by Dexus** [comment]
> I am good with merging this and then working on moving the APK build over. I just need to setup the secrets in this repo before I merge this.

Please make sure this Secrets also setup for the GVM-APK-build is done.

**Pull request merged**
